import { useRef, useState } from 'react';
import { Link, Navigate } from 'react-router-dom';
import Seo from '../components/Seo';
import { useStore } from '../context/StoreContext';
const emailRx=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
export default function Checkout(){
  const {lines,subtotal,clearCart}=useStore(); const started=useRef(Date.now()); const [done,setDone]=useState(false); const [error,setError]=useState('');
  const [details,setDetails]=useState({name:'',email:'',phone:'',business:'',notes:'',website:''});
  if(!lines.length&&!done)return <Navigate to="/store" replace/>;
  const update=(k,v)=>{setError('');setDetails(x=>({...x,[k]:v}))};
  const submit=e=>{e.preventDefault();if(details.website)return;if(Date.now()-started.current<2500){setError('Give the order form a moment, then try again.');return}if(details.name.trim().length<2||details.business.trim().length<2){setError('Add your name and business name.');return}if(!emailRx.test(details.email.trim())){setError('Add a valid email address.');return}if(details.phone.trim().length<7){setError('Add a valid phone number.');return}const ref=`CV-${Date.now().toString().slice(-6)}`;const items=lines.map(l=>`${l.product.name} / ${l.tier.label} x${l.qty} — R${l.lineTotal}`).join('\n');const msg=`CODEVENIENT PROJECT ORDER ${ref}\n\n${items}\n\nSubtotal: R${subtotal}\n\nName: ${details.name}\nBusiness: ${details.business}\nEmail: ${details.email}\nPhone: ${details.phone}\nNotes: ${details.notes}`;window.open(`https://wa.me/27603168301?text=${encodeURIComponent(msg)}`,'_blank','noopener,noreferrer');clearCart();setDone(ref)};
  if(done)return <div className="checkout-page"><Seo title="Order issued — Codevenient Store" noindex/><div className="container order-complete"><span className="brief-stamp">ORDER ISSUED</span><p className="label">Reference / {done}</p><h1>Specification sent.</h1><p>Your project order has been prepared and WhatsApp opened with the full breakdown. This checkout intentionally does not collect payment yet.</p><Link className="btn btn-primary" to="/store">Return to store</Link></div></div>;
  return <div className="checkout-page"><Seo title="Project order — Codevenient Store" noindex/><div className="container checkout-grid"><form className="checkout-form" onSubmit={submit} noValidate><p className="label">Project order / Checkout</p><h1>Confirm the specification.</h1><p className="checkout-intro">No payment is collected in this version. The confirmed order is sent to Codevenient for invoice and fulfilment.</p><div className="field-row"><label>NAME<input value={details.name} onChange={e=>update('name',e.target.value)} autoComplete="name"/></label><label>BUSINESS<input value={details.business} onChange={e=>update('business',e.target.value)} autoComplete="organization"/></label></div><div className="field-row"><label>EMAIL<input type="email" value={details.email} onChange={e=>update('email',e.target.value)} autoComplete="email"/></label><label>PHONE<input value={details.phone} onChange={e=>update('phone',e.target.value)} autoComplete="tel"/></label></div><label>ORDER NOTES<textarea rows="4" value={details.notes} onChange={e=>update('notes',e.target.value)} placeholder="Domain, preferred colours, delivery notes..."/></label><label className="hp-field" aria-hidden="true">Website<input tabIndex="-1" autoComplete="off" value={details.website} onChange={e=>update('website',e.target.value)}/></label>{error&&<p className="form-message error" role="alert">{error}</p>}<button className="btn btn-primary checkout-submit">Issue project order →</button></form><aside className="checkout-summary"><div className="pricing-head"><span>ORDER DRAWING</span><b>{String(lines.length).padStart(2,'0')} LINES</b></div>{lines.map(l=><div className="summary-line" key={l.key}><span>{l.product.ref}<b>{l.product.name}</b><small>{l.tier.label} × {l.qty}</small></span><strong>R{l.lineTotal.toLocaleString()}</strong></div>)}<div className="summary-total"><span>SUBTOTAL</span><strong>R{subtotal.toLocaleString()}</strong></div><p>Source licences are for one end product unless otherwise agreed. Launch packages are confirmed after content and domain checks.</p></aside></div></div>;
}
