import { useEffect, useState } from 'react';
import { useLocation, Link } from 'react-router-dom';
import Reveal from '../components/Reveal';
import Seo from '../components/Seo';
import Crosshairs from '../components/Crosshairs';
import ReadySystems from '../components/ReadySystems';
import ClientLogos from '../components/ClientLogos';

function ContactForm(){
  const [status,setStatus]=useState('idle');
  const [error,setError]=useState('');
  const [startedAt]=useState(()=>Date.now());
  const submit=e=>{
    e.preventDefault(); setError('');
    const d=new FormData(e.currentTarget);
    if(d.get('website')) return;
    const name=d.get('name')?.toString().trim()||''; const phone=d.get('phone')?.toString().trim()||''; const email=d.get('email')?.toString().trim()||''; const message=d.get('message')?.toString().trim()||'';
    if(Date.now()-startedAt<2500){setError('Give the form a moment, then try again.');return}
    if(name.length<2){setError('Add your name.');return}
    if(phone.length<7){setError('Add a valid phone number.');return}
    if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){setError('Add a valid email address.');return}
    if(message.length<15){setError('Tell us a little more about what you want to build.');return}
    const msg=[`Name: ${name}`,`Phone: ${phone}`,`Email: ${email}`,`Message: ${message}`].join('\n');
    window.open(`https://wa.me/27603168301?text=${encodeURIComponent(msg)}`,'_blank','noopener,noreferrer');setStatus('sent');e.currentTarget.reset();
  };
  return <form className="oform" onSubmit={submit} noValidate><input name="name" placeholder="Name" autoComplete="name"/><input name="phone" placeholder="Phone" autoComplete="tel"/><input type="email" name="email" placeholder="Email" autoComplete="email"/><textarea name="message" rows="3" placeholder="What are you looking to build?"/><label className="hp-field" aria-hidden="true">Website<input name="website" tabIndex="-1" autoComplete="off"/></label>{error&&<p className="form-message error" role="alert">{error}</p>}<button className="btn btn-primary">{status==='sent'?'WhatsApp opened ✓':'Start a project →'}</button></form>;
}

export default function Home(){const location=useLocation();useEffect(()=>{if(location.state?.scrollTo){const t=setTimeout(()=>document.getElementById(location.state.scrollTo)?.scrollIntoView({behavior:'smooth'}),60);return()=>clearTimeout(t)}},[location.state]);return <>
<Seo title="Codevenient Consulting — Strategy, Design, Build & Ready Systems" description="Websites, ecommerce, apps and ready-built digital systems for small businesses."/>
<header className="hero" id="top"><div className="container hero-inner"><div className="hero-copy"><Reveal><p className="label">Sheet 01 — Overview</p></Reveal><Reveal><h1>We draft it properly<br/>before we <span>build</span> it</h1></Reveal><Reveal><p className="lead">Codevenient designs and engineers websites, booking systems and online stores for small businesses — now with ready-built systems that let you start further ahead.</p></Reveal><Reveal><div className="hero-actions"><a className="btn btn-primary" onClick={()=>document.getElementById('contact')?.scrollIntoView({behavior:'smooth'})}>Start a project</a><Link className="technical-link hero-secondary-link" to="/store">Explore ready systems →</Link></div></Reveal></div><Reveal><div className="blueprint"><Crosshairs/><div className="bp-diagram"><svg viewBox="0 0 480 360"><rect className="draw-line" x="20" y="20" width="440" height="300" rx="6" fill="none" stroke="#1F4E79" strokeWidth="1.5"/><line className="draw-line d2" x1="20" y1="54" x2="460" y2="54" stroke="#1F4E79"/><rect className="draw-line d3" x="44" y="80" width="180" height="90" rx="3" fill="none" stroke="#1F4E79"/><rect className="draw-line d3" x="240" y="80" width="196" height="42" rx="3" fill="none" stroke="#1F4E79"/><rect className="draw-line d3" x="240" y="128" width="196" height="42" rx="3" fill="none" stroke="#1F4E79"/><rect className="draw-line d4" x="44" y="212" width="130" height="34" rx="3" fill="none" stroke="#1F4E79"/><rect className="draw-line d4" x="184" y="212" width="130" height="34" rx="3" fill="none" stroke="#1F4E79"/><rect className="draw-line d4" x="324" y="212" width="112" height="34" rx="3" fill="none" stroke="#1F4E79"/><rect className="fade-in-el" x="44" y="264" width="120" height="30" rx="4" fill="#D9552E"/></svg><span className="bp-callout c1"><span className="dot"/>100% responsive</span><span className="bp-callout c2"><span className="dot"/>ready to customise</span><span className="bp-callout c3"><span className="dot"/>built to convert</span></div><div className="title-block"><span>DRAWN FOR: SMALL BUSINESS · SCALE: N.T.S.</span><span><b>CODEVENIENT</b> REV. 04</span></div></div></Reveal></div></header>
<section className="spec-strip"><div className="container spec-row"><span>Built for — <b>wellness</b></span><span><b>retail</b></span><span><b>hospitality</b></span><span><b>trades</b></span><span><b>professional services</b></span></div></section>
<section className="section" id="services"><div className="container"><Reveal><div className="head-row"><h2>Three drawings, one build team</h2><p className="sub">No handoffs between “the designer” and “the developer” — every project is scoped, designed and shipped by the same small team.</p></div></Reveal><Reveal><div className="sheets-grid">{[['Fig. 01 — Brand sites','Marketing & brand sites','A fast, distinctive site that earns trust before a visitor reads a word — built to rank and convert on mobile.','LOAD < 1.5s · MOBILE-FIRST'],['Fig. 02 — Booking systems','Booking & scheduling','Calendars, deposits and reminders handled automatically, so appointments fill themselves while you run the business.','AUTOMATED · NO DOUBLE-BOOKINGS'],['Fig. 03 — Online stores','E-commerce builds','Catalogue, checkout and stock wired together and tuned to sell wherever your customers already shop.','SECURE CHECKOUT · STOCK-READY']].map(x=><div className="sheet" key={x[0]}><Crosshairs/><span className="sheet-tag">{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p><div className="sheet-spec">{x[3]}</div></div>)}</div></Reveal></div></section>
<section className="section section-tight" id="process"><div className="container"><Reveal><div className="head-row"><h2>Four revisions to a finished build</h2><p className="sub">Four deliberate stages — from first call to something live, measurable and ready to improve.</p></div></Reveal><Reveal><div className="ruler-wrap"><div className="ruler-line"/><div className="ruler">{[['01','Discover','We map the customer and the friction stopping people from booking or buying.'],['02','Design','A working prototype — not a mood board — so real decisions happen early.'],['03','Build','Development stays visible, tested and responsive across the devices that matter.'],['04','Grow','Launch is day one. We measure, learn and keep improving.']].map(r=><div className="rev" key={r[0]}><span className="rev-tag">Rev. {r[0]}</span><h3>{r[1]}</h3><p>{r[2]}</p></div>)}</div></div></Reveal></div></section>
<ReadySystems/>
<section className="section-tight" id="results"><div className="container"><Reveal><p className="label result-label">Spec sheet — what we optimise for</p><div className="spec-table"><div className="spec-table-row"><div className="spec-cell"><div className="num">100<span>%</span></div><div className="lbl">Responsive systems</div></div><div className="spec-cell"><div className="num">3<span> paths</span></div><div className="lbl">Source / launch / custom</div></div><div className="spec-cell"><div className="num">10<span>+</span></div><div className="lbl">Ready system foundations</div></div><div className="spec-cell"><div className="num">1<span> team</span></div><div className="lbl">Strategy through deployment</div></div></div></div></Reveal></div></section>
<section className="section" id="work"><div className="container"><Reveal><div className="head-row"><h2>Work that became reusable knowledge</h2><p className="sub">Client builds taught us which patterns repeat across industries. The store packages those patterns instead of restarting from zero.</p></div></Reveal><Reveal><div className="notes-grid"><div className="note"><div className="note-head"><span className="label">Field note</span><span className="approved">PRODUCTISED</span></div><p className="quote">Legal, security, retail and creative businesses rarely need a blank canvas. They need the right foundation and the right tailoring.</p><div className="note-foot"><div><b>Codevenient systems</b><span>Reusable industry foundations</span></div><div className="note-result">LESS REWORK</div></div></div><div className="note"><div className="note-head"><span className="label">Field note</span><span className="approved">CUSTOM</span></div><p className="quote">When a ready system gets you 70% there, the remaining budget can go into the features that actually make your business different.</p><div className="note-foot"><div><b>Make it mine</b><span>Tailored implementation</span></div><div className="note-result">MORE VALUE</div></div></div></div></Reveal></div></section>
<ClientLogos/>
<section className="section" id="contact"><div className="container"><Reveal><div className="order-band"><div><p className="label">Start a project</p><h2>Tell us where the business is stuck. We'll tell you what we'd draft first.</h2><p className="copy">Start custom, or point us at a ready-built system and tell us what needs to change.</p><Link to="/custom-build" className="technical-link light-link">OPEN PROJECT BRIEF →</Link></div><ContactForm/></div></Reveal></div></section>
</>}
