import { Link, Navigate, useParams } from 'react-router-dom';
import Seo from '../components/Seo';
import Crosshairs from '../components/Crosshairs';
import ProductVisual from '../components/ProductVisual';
import ProductCard from '../components/ProductCard';
import { getProduct, products } from '../data/products';
import { useStore } from '../context/StoreContext';

export default function ProductDetail(){const {id}=useParams();const product=getProduct(id);const {wishlist,toggleWishlist,addToCart}=useStore();if(!product)return <Navigate to="/store" replace/>;const related=products.filter(p=>p.id!==product.id&&(p.category===product.category||p.industry===product.industry)).slice(0,3);return <>
<Seo title={`${product.name} — Codevenient Store`} description={product.summary}/>
<header className="product-hero"><div className="container"><div className="crumb"><Link to="/store">STORE INDEX</Link><span>/</span><b>{product.ref}</b></div><div className="product-hero-grid"><div><div className="product-title-line"><p className="label">{product.ref} — {product.industry}</p><button className={`save-product ${wishlist.includes(product.id)?'saved':''}`} onClick={()=>toggleWishlist(product.id)}>{wishlist.includes(product.id)?'◆ SAVED':'◇ SAVE SYSTEM'}</button></div><h1>{product.name}</h1><p className="product-type">{product.type}</p><p className="lead">{product.description}</p><div className="product-tags">{product.tags.map(t=><span key={t}>{t}</span>)}</div></div><ProductVisual product={product} large/></div></div></header>
<section className="section product-spec-section"><div className="container"><div className="product-layout"><div className="product-main"><p className="label">System specification</p><h2>What's already engineered.</h2><div className="feature-drawing">{product.features.map((f,i)=><div key={f}><span>{String(i+1).padStart(2,'0')}</span><b>{f}</b></div>)}</div><div className="stack-block"><span>BUILD STACK</span>{product.stack.map(s=><b key={s}>{s}</b>)}</div></div><aside className="pricing-drawing"><Crosshairs/><div className="pricing-head"><span>PROCUREMENT / {product.ref}</span><b>SELECT PATH</b></div>{product.tiers.map(t=><div className={`tier ${t.id==='launch'?'recommended':''}`} key={t.id}><div className="tier-top"><span>{t.label.toUpperCase()}</span>{t.id==='launch'&&<em>RECOMMENDED</em>}</div><strong>{t.price?`R${t.price.toLocaleString()}`:'QUOTE'}</strong><p>{t.note}</p>{t.id==='custom'?<Link className="btn btn-outline" to={`/custom-build?system=${product.id}`}>Tailor this system →</Link>:<button className="btn btn-primary" onClick={()=>addToCart(product.id,t.id)}>Add {t.label.toLowerCase()} →</button>}</div>)}<div className="pricing-foot">DIGITAL PRODUCT / LICENCE FOR ONE END PROJECT · CUSTOM COMMERCIAL TERMS AVAILABLE</div></aside></div></div></section>
<section className="section related-section"><div className="container"><div className="head-row"><h2>Adjacent drawings</h2><Link to="/store" className="technical-link">FULL CATALOGUE →</Link></div><div className="ready-grid">{related.map(p=><ProductCard key={p.id} product={p} compact/>)}</div></div></section>
</>}
